### ISSUE TITLE
add documentation (comments) for variables in quick-view/hover

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/superbol-studio-oss#339]
example:

```cobol
      * some line comment
       77 NUM-FLD      PIC S9(35)v9.

       01 FLD-X7.
      *  03 FLD-97     PIC S9(5)v9(32).
         03 FLD-97     PIC S9(02)V9(35).   *> some comment

       PROCEDURE DIVISION.
           MOVE -1234                  TO FLD-97.
           MOVE -1234                  TO NUM-FLD.
```

So when hovering over FLD-97 it would be nice to see "some comment", when hovering over NUM-FLD the "some line comment" would be the appropriate doc.
The line comment gets special for commented code, which  "obviously" should be skipped (which is possibly hard, showing the much less used inline comments would at least be an improvement)

**Comment by GitMensch** [comment]
Applying the same to procedures would be nice, too.

**Comment by nberth** [comment]
Many thanks that's an interesting suggestion ;-)

Details (@NeoKaios may be interested): there is a (reversed) list of comments that can be accessed as `artifacts.rev_comments` https://github.com/OCamlPro/superbol-studio-oss/blob/1828439139dbf0eec891ba41109241a284f10ee0/src/lsp/cobol_lsp/lsp_document.ml#L26
The locations in there are `lexloc`, so there is a need for an equality check on the filename instead of a projection like on "general" source locations.

**Comment by GitMensch** [comment]
As there were some adjustments in this area like #297 solving this would likely be a good point in time to check/update/add hovers in the README screenshots/text.
