### ISSUE TITLE
syntaxes/COBOL.tmLanguage.json

### ISSUE THREAD

**Issue by spgennard** [OCamlPro/superbol-studio-oss#34]
Please note, this this grammar is not for the GnuCOBOL dialect but is for Micro Focus/OpenText based compilers.   

It includes many reserved words that are not appropriate for GnuCOBOL and will cause inconsistencies with the lsp.

**Comment by spgennard** [comment]
> Things I've seen "on a glance": all `EXEC` but `EXEC SQL` (there are good preparsers available for that) and OO COBOL.
> On the other hand: having it highlighted nicely and then get an error by the LSP / compiler may not be that bad, is it?

Colourisation of source code should reflect the viability of the source to compile clearly, clearly using the wrong variant of a language will ensure this happens unexpectedly.

One key aspect of this is that different dialects of COBOL impacts colourisation of storage fields etc.. due to keyword, reserved words differences.

**Comment by spgennard** [comment]
> This file was copied there to have a working extension as fast as possible, we plan to have this file generated automatically as soon as possible from keyword and other declarations within SuperBOL.

That would be more accurate and inline with the LSP.

> Yet, GnuCOBOL has support for the Micro Focus dialect, so users may want to use GnuCOBOL support in SuperBOL together with Micro Focus dialect, no ?
> 

GnuCOBOL's Micro Focus dialect support is limited and implemented in a haphazard manor.   The genuine version has many levels of support rather than just one.

**Comment by GitMensch** [comment]
> GnuCOBOL's Micro Focus dialect support is limited and implemented in a haphazard manor. The genuine version has many levels of support rather than just one.

While this is a topic drift: Can you please elaborate on that? What part of the implementation do you consider that bad and what do you mean with "many levels of support"?

**Comment by spgennard** [comment]
> > This file was copied there to have a working extension as fast as possible, we plan to have this file generated automatically as soon as possible from keyword and other declarations within SuperBOL.
> 
> That would be more accurate and inline with the LSP.

Meanwhile, this might help: https://github.com/spgennard/vscode_cobol4gnucobol/tree/main/syntaxes

> 
> > Yet, GnuCOBOL has support for the Micro Focus dialect, so users may want to use GnuCOBOL support in SuperBOL together with Micro Focus dialect, no ?
> 
> GnuCOBOL's Micro Focus dialect support is limited and implemented in a haphazard manor. The genuine version has many levels of support rather than just one.

**Comment by spgennard** [comment]
@lefessan What do think?

I think the options for resolving this issue are:
 - ignore this and continue to use it
 - switch to a GnuCOBOL specific textmate grammar
   - and replace later with a generated one
 - something else you suguest?

**Comment by lefessan** [comment]
As I said before, we are not focusing only on the GnuCOBOL dialect, but want SuperBOL to provide some support for all dialects that could be used by GnuCOBOL. We need to think about a way to get rid of this file, probably by generating it as we do for `package.json`, but there is no urgency, especially given that the mode is not yet publicly distributed on Vscode marketplaces. 

Moreover, I am not completely convinced that highlighting extra keywords is really a problem: it can actually be useful for a developer to know that some keyword is not meaningful in its own dialect, but could be in another one, as it might make later migration more difficult.

Also, since highlighting is already performed by the LSP in SuperBOL, I am not sure what this file is really used for by vscode.  Since the LSP gives a color for all words, I expect this color to always be chosen instead of the one generated from this file.

**Comment by GitMensch** [comment]
> Also, since highlighting is already performed by the LSP in SuperBOL, I am not sure what this file is really used for by vscode.

Even if it isn't normally used, it likely is at least used if there is a file opened from an untrusted workspace (those editor windows commonly don't t run with external LSPs for security considerations) and used if this extension will be made available as a web-extension later (which doesn't work with external LSPs).

**Comment by spgennard** [comment]
> this extension will be made available as a web-extension later (which doesn't work with external LSPs).

@GitMensch You should check your facts, this is not 100% true, GitHub Codespaces in Visual Studio Code for Web does.

**Comment by GitMensch** [comment]
@spgennard Are you sure that this is still a web-extension then? As far as I know Github "edit" uses vscode-web which will use only web extensions, and Codespaces (as the older and quite nice Gitpod) don't use vscode-web extensions but is a full-featured vscode running in a docker container, so you have a full environment (including shell terminals, complete C/Python/GnuCOBOL/[and/or MicroFocus if you get it into that container] ...  environments) that doesn't use the web extension entrypoints at all.

Maybe I was not clear that I've talked about "plain" vscode-web and web-extensions?

Or maybe I've misunderstood something. Please elaborate as I always like to learn something new, especially if I otherwise misread facts and retell it that way.

**Comment by spgennard** [comment]
@GitMensch Yes, I am 100% sure... it would be best if you revisited your assumption about GitHub Codespaces... no point in me re-writing what GitHub have in their documentation.

**Comment by spgennard** [comment]
Any update?

**Comment by nberth** [comment]
#200 temporarily uses this file almost unmodified.

Note that this file is only used to colorize pieces of code for which the LSP server does not assign semantic tokens (or if the latter are manually disabled by the user); at the moment that is mostly for copybooks, and code shown in tooltips. Having an approximate grammar just for these rare colorization cases should not be too much of an issue.

Moreover, what is not recognized as consistent *w.r.t* the configured dialect shall be associated with syntax error/warning diagnostics directly issued from the LSP server — when such diagnostics will be re-enabled, which is when the internal grammar of the server will be completely aligned with that of GnuCOBOL.
